package Pojo;
// Generated Jan 28, 2021 11:26:29 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Chat generated by hbm2java
 */
public class Chat  implements java.io.Serializable {


     private String chatId;
     private String name;
     private Date dateCreated;

    public Chat() {
    }

    public Chat(String chatId, String name, Date dateCreated) {
       this.chatId = chatId;
       this.name = name;
       this.dateCreated = dateCreated;
    }
   
    public String getChatId() {
        return this.chatId;
    }
    
    public void setChatId(String chatId) {
        this.chatId = chatId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getDateCreated() {
        return this.dateCreated;
    }
    
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }




}


